//Copyright © 2019 Vincode, Inc. All rights reserved.

import Foundation

class OPMLDocument: OPMLEntry {
	
	override func makeXML(indentLevel: Int) -> String {
		
		var s =
		"""
		<?xml version="1.0" encoding="UTF-8"?>
		<!-- Generated by Feed Curator -->
		<opml version="1.1">
		<head>
		<title>\(title ?? "")</title>
		</head>
		<body>
		
		"""
		
		for entry in entries {
			s += entry.makeXML(indentLevel: indentLevel + 1)
		}

		s +=
		"""
			</body>
			</opml>
			"""
		
		return s
		
	}
	
	func entry(for address: OPMLEntryAddress) -> OPMLEntry {
		var result: OPMLEntry = self
		for i in address {
			result = result.entries[i]
		}
		return result
	}
	
}
